export const MAKE_ACTUAL = 'CONTROL/MAKE_ACTUAL';
export const SWITCH_THEME = 'CONTROL/SWITCH_THEME';

export const DRAW_DISPLAY = 'DISPLAY/DRAW_DISPLAY';
export const DRAW_HISTORY_DISPLAY = 'DISPLAY/DRAW_HISTORY_DISPLAY';
export const CHANGE_SIGN = 'DISPLAY/CHANGE_SIGN';
export const CLEAR_CURRENT = 'DISPLAY/CLEAR_CURRENT';
export const CLEAR_DISPLAY = 'DISPLAY/CLEAR_DISPLAY';
export const CLEAR_HISTORY = 'DISPLAY/CLEAR_HISTORY';
export const CLEAR_ALL = 'DISPLAY/CLEAR_ALL';
export const START_EXPRESSION = 'DISPLAY/START_EXPRESSION';
