export const SWITCH_THEME = 'SWITCH_THEME';
export const TOGGLE_HISTORY_MODULE = 'TOGGLE_HISTORY_MODULE';

export const DRAW_DISPLAY = 'DRAW_DISPLAY';
export const DRAW_HISTORY_DISPLAY = 'DRAW_HISTORY_DISPLAY';
export const DRAW_HISTORY = 'DRAW_HISTORY';
export const CLEAR_DISPLAY = 'CLEAR_DISPLAY';
export const CLEAR_HISTORY = 'CLEAR_HISTORY';
