export const SWITCH_THEME = 'SWITCH_THEME';
export const TOGGLE_HISTORY_MODULE = 'TOGGLE_HISTORY_MODULE';

export const SET_DISPLAY_VALUE = 'SET_DISPLAY_VALUE';
export const SET_HISTORY_DISPLAY_VALUE = 'SET_HISTORY_DISPLAY_VALUE';
export const ADD_ITEM_HISTORY_LIST = 'ADD_ITEM_HISTORY_LIST';
export const CLEAR_DISPLAY = 'CLEAR_DISPLAY';
export const CLEAR_HISTORY = 'CLEAR_HISTORY';
